export const GAME_STARTGAME = 'GAME_STARTGAME';
export const GAME_SETPLAYER1 = 'GAME_SETPLAYER1';
export const GAME_SETPLAYER2 = 'GAME_SETPLAYER2';
export const GAME_GETQUESTION = 'GAME_GETQUESTION';

export const GAME_CONNECT = 'GAME_CONNECT';
export const GAME_PENDING = 'GAME_PENDING';
export const GAME_DISCONNECT = 'GAME_DISCONNECT';
export const GAME_UPDATESCORE = 'GAME_UPDATESCORE';