export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SAVEUSERINFO = 'USER_SAVEUSERINFO';
export const USER_REMOVEUSERINFO = 'USER_REMOVEUSERINFO';
export const USER_UPDATEINFO = 'USER_UPDATEINFO';
export const USER_GOCHANGEINFO = 'USER_GOCHANGEINFO';
export const USER_BACKCHANGEINFO = 'USER_BACKCHANGEINFO';


export const USER_FETCHINFO = 'USER_LOGOUT';
export const USER_FETCHSCORES = 'USER_LOGOUT';
export const USER_CHANGEPASSWORD = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_LOGOUT';

